MAX_DELAY = 30

FORMAT_DATE = '%Y-%m-%d'
FORMAT_DATETIME = '%Y-%m-%d %H:%M:%S'

RABBITMQ_EXCHANGE_NAME = 'social_listening'
RABBITMQ_EXCHANGE_TYPE = 'direct'
RABBITMQ_MONITOR_QUEUE = 'monitor_queue'
RABBITMQ_TASK_QUEUE = 'task_queue'
RABBITMQ_RISK_QUEUE = 'risk_queue'
RABBITMQ_QUEUE_DURABLE = True
RABBITMQ_DELIVERY_MODE = 2

MQTT_TOPIC_TASK = 'task'
MQTT_TOPIC_JOB_UPDATE = 'job/update'

PROJECT = 'facebook_v1.1'
MAX_PAGINATION_ARTICLE_DEPTH = 1
MAX_PAGINATION_COMMENT_DEPTH = 2
MAX_PAGINATION_REPLY_DEPTH = 2
USER_AGENT = 'Nokia6303iclassic/5.0 (10.80) Profile/MIDP-2.1 Configuration/CLDC-1.1 Opera/9.80 (J2ME/MIDP; Opera Mini/7.1.32052/35.6172; U; en) Presto/2.8.119 Version/11.10en9.4.0.342 UNTRUSTED/1.0'


# Status for JOB
JOB_STATUS_STARTED_SUCCESSFULLY = 1
JOB_STATUS_STARTED_FAILED = 2

# Error code for JOB
JOB_ERROR_CODE_EXCEED_VALID_EXECUTED_AT = 802